In [4]:
import numpy as np # One data type, think array
a = np.zeros(4) # create array of four zeros. 1 Dimension
print(a.shape) # Shape returns number of indeces. Only 1 dimension]
print(a.shape[0]) # Returns the number horizontal size (tuple)
c = np.random.random_sample(4) # Four random numbers between 0-1
print(c)

(4,)
4
[0.21804046 0.51377992 0.03092755 0.68477926]


In [5]:
x_train = np.array([3, 4, 5, 6, 7]) # Create an array and populate
print(x_train)
print(f"x_train is: {x_train}") # Like printf() in c

[3 4 5 6 7]
x_train is: [3 4 5 6 7]


In [6]:
d = np.arange(10)
print(d)
print(d[-1]) # Last element: shortcut for len(d - 1)
print(d[9]) # Last element

[0 1 2 3 4 5 6 7 8 9]
9
9


# Slicing arrays

### (start:end:step)

In [7]:
print(d[0:8:2])
print(d[3:])
print(d[:])

[0 2 4 6]
[3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [8]:
vec = np.array([2, 3, 4, 5, 6]) 
newVec = 3 * vec
print(vec) # Original vector
print(newVec) # Vector times 3
print(-vec) # Negative vector
print(np.sum(vec)) # Summation of vec
print(np.mean(vec)) # Mean of vec
print(np.std(vec)) # Standard deviation of vce

[2 3 4 5 6]
[ 6  9 12 15 18]
[-2 -3 -4 -5 -6]
20
4.0
1.4142135623730951


In [9]:
a = np.array([1, 2, 3]) # Arrays must be the same size to do math for each
b = np.array([4, 5, 6])

c = a + b
print(c)

[5 7 9]


In [10]:
c = a * b
print(c)

[ 4 10 18]


In [11]:
a = np.random.rand(1000000) # two vectos with 1mil random vars
b = np.random.rand(1000000)
c = np.dot(a, b) # Multiply the two vectors (maybe summation as well? look into this)
print(c)
print(f'The shape of b vector is{b.shape}')




250197.30789806513
The shape of b vector is(1000000,)


In [18]:
two_d = np.random.random_sample((3,5)) # Fill 2D matrix with random values
print(two_d)
print(f'The shape of two_d matrix is{two_d.shape}')
print(f'The shape of two_d[1] is {two_d.shape[1]}')
print(f'Value of two_d[2][3] is {two_d[2][3]}')

[[0.78895353 0.99713313 0.7769556  0.42149464 0.10992846]
 [0.5110456  0.10184123 0.00114213 0.02559992 0.06442974]
 [0.63980142 0.59624637 0.52660019 0.35617315 0.58700271]]
The shape of two_d matrix is(3, 5)
The shape of two_d[1] is 5
Value of two_d[2][3] is 0.3561731503424018


In [22]:
z = np.arange(8)
print(z.shape)
zz = z.reshape(-1,4) # Reshape array into a 2D array with however needed rows and 4 columns
                     # -1 symbolizes 'do the math for me'
print(zz.shape)

(8,)
(2, 4)


In [24]:
arr = np.arange(20).reshape(-1, 10) # Another reshaping example
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [27]:
print(arr[0][2:5]) # Slicing the array; getting 3 4 5 from first row
print(arr[0][:]) # Print whole first row

[2 3 4]
[0 1 2 3 4 5 6 7 8 9]
